In [24]:
import os 
import glob 
import pickle
from tqdm import tqdm
import numpy as np

In [115]:
# FILE CONCATENATOR
cwd =  '/media/data_cifs/afengler/data/kde/ddm/method_comparison/'
nexp = 1
nreps = 1
n_samples = 3000
file_signature = 'post_samp_perturbation_experiment_nexp_' + str(nexp) + '_n_' + str(n_samples) + '_*' 
out_file_signature = 'post_samp_perturbation_experiment_nexp_' + str(100) + '_nreps_1_n_' + str(n_samples) + '.pickle' 
print(file_signature)
files_ = glob.glob(cwd + file_signature)
print(files_)
cnt = 0
param_grids = []
data_grids = []
preds = []
meta_data = list()

for file_ in files_:
    #print(file_)
    tmp = pickle.load(open(file_, 'rb'))
    param_grids.append(np.expand_dims(tmp[0], axis = 0))
    data_grids.append(np.expand_dims(tmp[1], axis = 0))
    preds.append(np.expand_dims(tmp[2], axis = 0))
#     if cnt == 0:
#         meta_data = tmp[2]
#         cnt += 1
        
param_grid = np.array(param_grids)
data_grid = np.array(data_grids)
preds = np.array(preds)
#pickle.dump((param_grid, data_grid, meta_data), open(cwd + out_file_signature, 'wb'), protocol = 2)
pickle.dump((param_grid, data_grid, preds), open(cwd + out_file_signature, 'wb'), protocol = 2)

post_samp_perturbation_experiment_nexp_1_n_3000_*
['/media/data_cifs/afengler/data/kde/ddm/method_comparison/post_samp_perturbation_experiment_nexp_1_n_3000_53bb784d88-f5d8-11e9-9b2c-89046ff20708.pickle', '/media/data_cifs/afengler/data/kde/ddm/method_comparison/post_samp_perturbation_experiment_nexp_1_n_3000_9e73c89b8-f5bd-11e9-920a-893bf5c6c890.pickle', '/media/data_cifs/afengler/data/kde/ddm/method_comparison/post_samp_perturbation_experiment_nexp_1_n_3000_25c138eb72-f5c6-11e9-a29b-b93e5718479b.pickle', '/media/data_cifs/afengler/data/kde/ddm/method_comparison/post_samp_perturbation_experiment_nexp_1_n_3000_6813daf9cc-f5e2-11e9-9130-ab227c6db3c8.pickle', '/media/data_cifs/afengler/data/kde/ddm/method_comparison/post_samp_perturbation_experiment_nexp_1_n_3000_63f8614154-f5d4-11e9-b140-85722610dc5d.pickle', '/media/data_cifs/afengler/data/kde/ddm/method_comparison/post_samp_perturbation_experiment_nexp_1_n_3000_51f1c0c192-f5d6-11e9-b6a4-6f5491d50b10.pickle', '/media/data_cifs/afengler

In [102]:
for data_grid in data_grids:
    print(data_grid.shape)

(1, 13, 250, 2)
(1, 13, 250, 2)
(1, 13, 250, 2)
(1, 13, 250, 2)
(1, 13, 250, 2)
(1, 13, 250, 2)
(1, 13, 250, 2)
(1, 13, 250, 2)
(1, 13, 250, 2)
(1, 13, 250, 2)
(1, 13, 250, 2)
(1, 13, 250, 2)
(1, 13, 250, 2)
(1, 13, 250, 2)
(1, 13, 250, 2)
(1, 13, 250, 2)
(1, 13, 250, 2)
(1, 13, 250, 2)
(1, 13, 250, 2)
(1, 13, 250, 2)
(1, 13, 250, 2)
(1, 13, 250, 2)
(1, 13, 250, 2)
(1, 13, 250, 2)
(1, 13, 250, 2)
(1, 13, 250, 2)
(1, 13, 250, 2)
(1, 13, 250, 2)
(1, 13, 250, 2)
(1, 13, 250, 2)
(1, 13, 250, 2)
(1, 13, 250, 2)
(1, 13, 250, 2)
(1, 13, 250, 2)
(1, 13, 250, 2)
(1, 13, 250, 2)
(1, 13, 250, 2)
(1, 13, 250, 2)
(1, 13, 250, 2)
(1, 13, 250, 2)
(1, 13, 250, 2)
(1, 13, 250, 2)
(1, 13, 250, 2)
(1, 13, 250, 2)
(1, 13, 250, 2)
(1, 13, 250, 2)
(1, 13, 250, 2)
(1, 13, 250, 2)
(1, 13, 250, 2)
(1, 13, 250, 2)
(1, 13, 250, 2)
(1, 13, 250, 2)
(1, 13, 250, 2)
(1, 13, 250, 2)
(1, 13, 250, 2)
(1, 13, 250, 2)
(1, 13, 250, 2)
(1, 13, 250, 2)
(1, 13, 250, 2)
(1, 13, 250, 2)
(1, 13, 250, 2)
(1, 13, 250, 2)
(1, 13, 

In [96]:
data_grids[0, :, :, :]

TypeError: list indices must be integers or slices, not tuple

In [34]:
test = np.array(param_grids)

In [30]:
np.expand_dims(test, axis = 1).shape

(3, 1)

In [35]:
test.shape

(100, 1, 13, 4)

In [124]:
s = 1
np.zeros((3))[:] = 1.0

In [120]:
t

array([1., 1., 1.])

In [135]:
np.random.uniform(size = 10).astype(np.float32)

array([0.69240206, 0.02219047, 0.9090342 , 0.16239984, 0.2350252 ,
       0.6302917 , 0.28511032, 0.50074875, 0.31615797, 0.10656768],
      dtype=float32)

In [136]:
np.float32(np.random.uniform(size = 10))

array([0.9460555 , 0.7345241 , 0.39383292, 0.8820081 , 0.28323907,
       0.13430743, 0.79362   , 0.3032497 , 0.5787424 , 0.32368183],
      dtype=float32)

In [153]:
a = {'a': 10, 'b': 20}

In [139]:
a.pop('a')

10

In [146]:
if 'a' in a.keys():
    print('hello')

hello


In [145]:
a.keys()

dict_keys(['a', 'b'])

In [154]:
b = a.copy()


In [155]:
b

{'a': 10, 'b': 20}

In [156]:
b.pop('a')

10

In [157]:
a

{'a': 10, 'b': 20}

In [172]:
t = np.random.uniform(low = 0.5, high = 0.0, size = 100)

In [173]:
t

array([0.36508152, 0.08855611, 0.37185627, 0.38211775, 0.3322765 ,
       0.17844721, 0.38910915, 0.26674325, 0.11731493, 0.30679182,
       0.03206849, 0.39457146, 0.24758699, 0.4064238 , 0.40824798,
       0.10314418, 0.39231826, 0.03082251, 0.07738817, 0.4207353 ,
       0.18848036, 0.0466662 , 0.31549642, 0.13006441, 0.27762197,
       0.07186626, 0.31390029, 0.17817106, 0.17757161, 0.23572943,
       0.32082105, 0.17827703, 0.17575709, 0.38152599, 0.31606054,
       0.43981349, 0.05138198, 0.18046642, 0.24470487, 0.16659555,
       0.36457043, 0.33066135, 0.22385974, 0.41799466, 0.25506451,
       0.08505351, 0.483184  , 0.05605949, 0.00385551, 0.34973035,
       0.29892381, 0.06128946, 0.17009357, 0.0268915 , 0.15976005,
       0.31952503, 0.48907443, 0.1278912 , 0.03202546, 0.04046004,
       0.46160635, 0.17037664, 0.3972776 , 0.34879272, 0.13840321,
       0.11044323, 0.3663074 , 0.17320812, 0.33931898, 0.03354025,
       0.04344675, 0.46083757, 0.10597399, 0.14509954, 0.30706